# Generated by Django 6.0 on 2025-12-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名组', max_length=200, verbose_name='主题/标题')),
                ('prompt_text', models.TextField(verbose_name='正向提示词 (Prompt)')),
                ('negative_prompt', models.TextField(blank=True, null=True, verbose_name='负向提示词 (Negative Prompt)')),
                ('model_info', models.CharField(blank=True, help_text='例如: Midjourney v6, Stable Diffusion XL', max_length=200, verbose_name='模型信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '提示词组',
                'verbose_name_plural': '提示词组列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prompts/', verbose_name='图片文件')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.promptgroup', verbose_name='所属提示词组')),
            ],
            options={
                'verbose_name': '单张图片',
                'verbose_name_plural': '图片集',
            },
        ),
    ]
