# Generated by Django 6.0 on 2025-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：风景、二次元、赛博朋克', max_length=30, unique=True, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签管理',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(upload_to='prompts/%Y/%m/%d/', verbose_name='图片文件'),
        ),
        migrations.AlterField(
            model_name='promptgroup',
            name='model_info',
            field=models.CharField(blank=True, help_text='例如: Midjourney v6', max_length=200, verbose_name='模型信息'),
        ),
        migrations.AddField(
            model_name='promptgroup',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='按住 Ctrl (或 Mac 上的 Command) 可多选', to='gallery.tag', verbose_name='关联标签'),
        ),
    ]
