# Generated by Django 6.0 on 2025-12-20 15:35

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_tag_alter_imageitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(upload_to=gallery.models.unique_file_path, verbose_name='图片文件'),
        ),
        migrations.AlterField(
            model_name='promptgroup',
            name='model_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='模型信息'),
        ),
        migrations.AlterField(
            model_name='promptgroup',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gallery.tag', verbose_name='关联标签'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='标签名'),
        ),
    ]
