# Generated by Django 6.0 on 2025-12-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_imageitem_image_alter_promptgroup_model_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如: Midjourney v6', max_length=50, unique=True, verbose_name='模型名称')),
                ('order', models.IntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序权重')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型管理',
                'ordering': ['-order', 'name'],
            },
        ),
    ]
