# Generated by Django 6.0 on 2025-12-20 18:12

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptgroup',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.reference_file_path, verbose_name='参考图 (垫图)'),
        ),
    ]
