# Generated by Django 6.0 on 2025-12-20 18:17

import django.db.models.deletion
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_promptgroup_reference_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageitem',
            options={'verbose_name': '生成图', 'verbose_name_plural': '生成图集'},
        ),
        migrations.RemoveField(
            model_name='promptgroup',
            name='reference_image',
        ),
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gallery.models.reference_file_path, verbose_name='参考图文件')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='gallery.promptgroup', verbose_name='所属提示词组')),
            ],
            options={
                'verbose_name': '参考图',
                'verbose_name_plural': '参考图集',
            },
        ),
    ]
