# Generated by Django 6.0 on 2025-12-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_imageitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='is_liked',
            field=models.BooleanField(default=False, verbose_name='是否喜欢'),
        ),
        migrations.AddField(
            model_name='promptgroup',
            name='is_liked',
            field=models.BooleanField(default=False, verbose_name='是否喜欢'),
        ),
    ]
