# Generated by Django 6.0 on 2025-12-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_imageitem_is_liked_promptgroup_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='feature_vector',
            field=models.BinaryField(blank=True, null=True, verbose_name='特征向量'),
        ),
    ]
