# Generated by Django 6.0 on 2025-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_imageitem_feature_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='MD5哈希'),
        ),
    ]
