# Generated by Django 6.0 on 2025-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_imageitem_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptgroup',
            name='prompt_text_zh',
            field=models.TextField(blank=True, null=True, verbose_name='中文/辅助提示词'),
        ),
    ]
