# Generated by Django 6.0 on 2025-12-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_promptgroup_prompt_text_zh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
