# Generated by Django 6.0 on 2026-01-10 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_promptgroup_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptgroup',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='组ID'),
        ),
    ]
