# Generated by Django 6.0 on 2026-02-08 13:00

import django.db.models.deletion
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_promptgroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptgroup',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_groups', to='gallery.imageitem', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.FileField(upload_to=gallery.models.unique_file_path, verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='image',
            field=models.FileField(upload_to=gallery.models.reference_file_path, verbose_name='参考文件'),
        ),
    ]
