# Generated by Django 6.0 on 2026-02-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_promptgroup_cover_image_alter_imageitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptgroup',
            name='is_main_variant',
            field=models.BooleanField(default=False, verbose_name='是否为主版本'),
        ),
    ]
