# Generated by Django 6.0 on 2026-03-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_promptgroup_is_main_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如: Tifa, 紫灵仙子, Ada Wong, 倪妮, 多人合集', max_length=50, unique=True, verbose_name='人物名称')),
                ('order', models.IntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序权重')),
            ],
            options={
                'verbose_name': '人物标签',
                'verbose_name_plural': '人物标签管理',
                'ordering': ['-order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='promptgroup',
            name='characters',
            field=models.ManyToManyField(blank=True, to='gallery.character', verbose_name='包含人物'),
        ),
    ]
