# Generated by Django 6.0 on 2026-03-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_character_promptgroup_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(help_text='例如: Tifa, 多人合集', max_length=50, unique=True, verbose_name='人物名称'),
        ),
    ]
