# Generated by Django 6.0 on 2026-03-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_alter_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptgroup',
            name='provider',
            field=models.CharField(blank=True, choices=[('fal_ai', 'Fal.ai'), ('volcengine', '火山引擎'), ('google_ai', 'Google AI'), ('midjourney', 'Midjourney'), ('webui', 'Stable Diffusion WebUI'), ('comfyui', 'ComfyUI'), ('other', '其他渠道')], default='other', max_length=50, verbose_name='生成渠道'),
        ),
    ]
