# Generated by Django 6.0 on 2026-03-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_promptgroup_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceitem',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='MD5哈希'),
        ),
        migrations.AlterField(
            model_name='promptgroup',
            name='provider',
            field=models.CharField(blank=True, choices=[('fal_ai', 'Fal.ai'), ('volcengine', '火山引擎'), ('google_ai', 'Google AI (API)'), ('gemini_web', 'Gemini 网页/APP'), ('midjourney', 'Midjourney'), ('webui', 'Stable Diffusion WebUI'), ('comfyui', 'ComfyUI'), ('other', '其他渠道')], default='other', max_length=50, verbose_name='生成渠道'),
        ),
    ]
